name: myfirst workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Greetings
        run: echo "Yu R Gt"

      - name: Exit the code
        run: echo "great work"
    
    
