name: myfirst workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Greetings
        run: |
          echo "Running multiline commands"
          echo "This is second command"
